---
version: "3.8"
services:
    runner:
        image: matthijsbos/nerdrage-dev
        volumes: 
            - type: bind
              source: "/var/run/docker.sock"
              target: "/var/run/docker.sock"
            - type: bind
              source: "."
              target: "/workspace"
        command: /bin/sh -c "while sleep 1000; do :; done"
        environment: 
            - "COMPOSE_PROJECT_NAME=nerdrage-webapp"
    mock:
        build: mock_controller/.
    webapp:
        build: .
        ports:
            - "8080:80"

    selenium:
        image: selenium/standalone-chrome:3.141.59
        shm_size: 2g
    crossbar:
        image: crossbario/crossbar
