---
version: "3.8"
services:
    runner:
        image: matthijsbos/nerdrage-dev
        volumes: 
            - type: bind
              source: "/var/run/docker.sock"
              target: "/var/run/docker.sock"
            - type: bind
              source: "."
              target: "/workspace"
        command: /bin/sh -c "while sleep 1000; do :; done"
        environment: 
            - "COMPOSE_PROJECT_NAME=nerdrage-webapp"
    mock:
        build: mock_controller/.
    webapp:
        build: .
        volumes:
            - type: bind
              source: "."
              target: "/nerdrage_webapp"
        working_dir: "/nerdrage_webapp"
        environment: 
            - "FLASK_APP=nerdrage_webapp.test"
            - "FLASK_ENV=development"
            - "FLASK_RUN_PORT=80"
            - "FLASK_RUN_HOST=0.0.0.0"
        command: flask run
    selenium:
        image: selenium/standalone-chrome:3.141.59
        shm_size: 2g
    crossbar:
        image: crossbario/crossbar
        ports: 
            - "8080:8080"
